spring.application.name=task-management-api
spring.mongodb.uri=${MONGODB_URI:mongodb://taskuser:taskpassword@localhost:27017/taskdb?authSource=taskdb}
spring.jackson.default-property-inclusion=NON_NULL
